BEGIN;

CREATE TABLE IF NOT EXISTS etl_runs
(
    id uuid PRIMARY KEY,
    status varchar(20) NOT NULL,
    mode varchar(20) NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NULL,
    error_summary varchar(200) NULL,
    etl_version varchar(30) NOT NULL,
    CONSTRAINT ck_etl_runs_status
        CHECK (status IN ('running', 'succeeded', 'failed', 'rejected', 'dry_run')),
    CONSTRAINT ck_etl_runs_mode
        CHECK (mode IN ('snapshot', 'incremental', 'dry_run'))
);

CREATE TABLE IF NOT EXISTS etl_entity_runs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES etl_runs(id),
    entity varchar(40) NOT NULL,
    status varchar(20) NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz NULL,
    cursor_start text NULL,
    cursor_end text NULL,
    pages integer NOT NULL DEFAULT 0,
    rows_read bigint NOT NULL DEFAULT 0,
    rows_inserted bigint NOT NULL DEFAULT 0,
    rows_updated bigint NOT NULL DEFAULT 0,
    rows_unchanged bigint NOT NULL DEFAULT 0,
    rows_rejected bigint NOT NULL DEFAULT 0,
    rows_deactivated bigint NOT NULL DEFAULT 0,
    error_summary varchar(200) NULL,
    CONSTRAINT uq_etl_entity_runs UNIQUE (run_id, entity),
    CONSTRAINT ck_etl_entity_runs_counts CHECK
    (
        pages >= 0 AND rows_read >= 0 AND rows_inserted >= 0
        AND rows_updated >= 0 AND rows_unchanged >= 0
        AND rows_rejected >= 0 AND rows_deactivated >= 0
    )
);

CREATE TABLE IF NOT EXISTS etl_checkpoints
(
    entity varchar(40) PRIMARY KEY,
    cursor_value text NULL,
    source_updated_since timestamptz NULL,
    last_successful_run_id uuid NULL REFERENCES etl_runs(id),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS etl_rejections
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES etl_runs(id),
    entity varchar(40) NOT NULL,
    natural_key_hash varchar(64) NULL,
    reason_code varchar(50) NOT NULL,
    reason_summary varchar(200) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS etl_staging_records
(
    run_id uuid NOT NULL REFERENCES etl_runs(id) ON DELETE CASCADE,
    entity varchar(40) NOT NULL,
    natural_key_hash varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    extracted_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
    PRIMARY KEY (run_id, entity, natural_key_hash)
);

CREATE INDEX IF NOT EXISTS ix_etl_runs_started_at ON etl_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS ix_etl_entity_runs_entity_started
    ON etl_entity_runs(entity, started_at DESC);
CREATE INDEX IF NOT EXISTS ix_etl_rejections_run_entity
    ON etl_rejections(run_id, entity);
CREATE INDEX IF NOT EXISTS ix_etl_staging_expires_at
    ON etl_staging_records(expires_at);

COMMIT;
